# fly.toml app configuration file generated for reactivities-project on 2023-09-26T15:30:36+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-project"
primary_region = "syd"

[build]
  image = "nisidazza/reactivities:latest"

[env]
ASPNETCORE_URLS="http://+:8080"
Cloudinary__CloudName="dqrzeowc6"
Cloudinary__ApiKey="526967782267699"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
